### ISSUE TITLE
Support config to select network interface

### ISSUE THREAD

**Issue by pvdvreede** [PSPDFKit-labs/bypass#11]
Hi there,

I am trying to use bypass with docker-compose and so have requests coming to bypass from another docker container. It seems like bypass only listens on the loopback so can only be called from the same container it is running in.

It would be great if there was a config option to set the interface (with loopback as the default) to facilitate this kind of integration testing between docker containers.

Thanks for your work!

**Comment by MSch** [comment]
We don't have that use case, but this should be a simple change if you are interested in sending a PR.

You just need to `Application.get_env` the interface here https://github.com/PSPDFKit-labs/bypass/blob/bd480059b7e862646eff0e7428452b17588b66ca/lib/bypass/instance.ex#L133 and add a default to the application's config https://github.com/PSPDFKit-labs/bypass/blob/bd480059b7e862646eff0e7428452b17588b66ca/mix.exs#L27
