### ISSUE TITLE
Test for no request?

### ISSUE THREAD

**Issue by nicksanders** [PSPDFKit-labs/bypass#14]
Is it possible to test for no request being made?

**Comment by alco** [comment]
@nicksanders It is possible. You need to set up a Bypass handler that always fails and then call `Bypass.pass` right after that. For example,

```elixir

  test "no request is sent" do
    bypass = Bypass.open
    Bypass.expect bypass, fn _conn ->
      flunk "This should not have happened"
    end
    Bypass.pass(bypass)

    assert :ok == do_something(url: "http://localhost:#{bypass.port}")
  end
```

If `do_something()` invokes the handler, you'll get a test failure. Otherwise, the test will pass.

**Comment by mbramson** [comment]
It would be wonderful if this was referenced somewhere in the documentation :). I do also think an `expect_never` function would fit in with the API nicely. It feels like a common enough thing to want to test for to deserve being a first class API function.
