### ISSUE TITLE
Hex metadata

### ISSUE THREAD

**Issue by alco** [PSPDFKit-labs/bypass#15]
I have a local branch with the following change:

```
-      maintainers: ["pspdfkit.com"],
+      maintainers: ["PSPDFKit GmbH"],
```

I don't remember if I simply forgot to push that or if we decided against it. I would like to propose this change again, and we can add a link to pspdfkit.com in the Links section.

**Comment by MSch** [comment]
I'm fine with `PSPDFKit` as maintainers, `PSPDFKit GmbH` just is too annoying. Please also add a link to the mix.exs. We'll then have it in the next release.
