### ISSUE TITLE
[Proposal] Support multiple expectation blocks with routing and more

### ISSUE THREAD

**Issue by alco** [PSPDFKit-labs/bypass#18]
## Background

Currently Bypass allows users to install a single `expect` handler that should be invoked one or more times to make the test containing it pass. The "one or more" semantics is not as strict as some people might expect.

Additionally, the current implementation cannot handle concurrent requests (see https://github.com/PSPDFKit-labs/bypass/issues/12). This behaviour is not intentional and it is desirable to support concurrent requests in order to accommodate for such use cases that require this. After all, testing with Bypass should not require changes to the application code and it's easy to imagine an application that has this behaviour by default.

Another limitation that has been reported is the inability to specify multiple routes on a single Bypass instance, see https://github.com/PSPDFKit-labs/bypass/issues/10. Supporting this functionality is also desirable in order to allow for testing more complex behaviours.

This proposal addresses those points by introducing several new functions.
## `expect/2` and `expect/4`
- `expect(bypass_instance, fn conn -> ... end)`
- `expect(bypass_instance, <method> | [<method>, ...], <route>, fn conn -> ... end)`

The first form works exactly the same as the existing function but it will support concurrent requests.

The second form allows installing multiple handlers so long as each one has a unique method-route combination, each of which has to be invoked at least once for the test to pass.
## `expect_once/2` and `expect_once/4`
- `expect_once(bypass_instance, fn conn -> ... end)`
- `expect_once(bypass_instance, <method> | [<method>, ...], <route>, fn conn -> ... end)`

The first form adds a handler that should be invoked exactly once for the test to pass.

The second form allows installing more than one handler as long as each one has a unique method-route combination. Each of the handlers has to be invoked exactly once in order for the test to pass.
## Notes
- Both `expect/4` and `expect_once/4` take one or more HTTP method names as strings. Passing a
  list means that requests that use any of the methods in the list will match.
  
  The `<route>` is a list of route segments. This allows for doing things like dynamic and
  wildcard segments without problem.
- All `expect/*` functions will return a handler ref. This ref will be accepted in calls to
  `pass`, `down`, and `up` allowing to selectively disable or pass each individual handler. Passing
  the Bypass instance to any of those functions will continue to work and will affect all
  handlers belonging to that instance at once.
- As a sample use case, by using the building blocks proposed here it is possible to build a state machine out of expectations by relying on an external storage for state. Here is an example using an Agent:
  
  ``` elixir
  import Bypass, except: [open: 0]
  import Plug.Conn, only: [resp: 3]
  
  test "multi-step request" do
    agent = Agent.start_link(fn -> 1 end)
    increment_fn = fn ->
      Agent.get_and_update(agent, fn step_no -> {step_no, step_no+1} end)
    end
  
    bypass = Bypass.open
    expect(bypass, "GET", ["foo"], fn conn ->
      case increment_fn.() do
        1 -> resp(conn, 404, "")
        4 -> resp(conn, 200, "")
        _ -> flunk "I didn't expect that"
      end
    end)
    expect_once(bypass, "GET", ["bar"], fn conn ->
      assert 2 == increment_fn.()
      resp(conn, 200, "")
    end)
    expect_once(bypass, "POST", ["foo"], fn conn ->
      assert 3 == increment_fn.()
      resp(conn, 200, "")
    end)
  
  
    HTTPClient.go(bypass.port)
  end
  ```

**Comment by gmile** [comment]
The bits regarding implementing `expect/4`, `expect_once/2` and `expect_once/4`: I imagine how I will do this, but do you have any particular implementation details in mind?

I think to solve this a list of all expectations should be kept in `Bypass.Instance`'s state. A structure to keep them would look like this:

```
list_of_expectations = %{
  once: %{ "GET /bar" => 0, "POST /foo" => 0 },
  once_or_more: %{ "GET /foo" => 0 }
}
```

This map would grow as new `Bypass.expect(bypass, ...)` expectations are declared during a given test case. Then, once the actual HTTP calls are submitted and the `.on_exit` callback is issued, the map is inspected. Upon inspections, all unmet expectations receive a nice message error, all of which are concatenated and revealed to the user (by means of `raise ExUnit.AssertionError, combined_message`.

A code to walk though the expectation and sample messages would look similar to this:

```elixir
list_of_expectations = %{
  once: %{
    "GET /bar" => 0,
    "POST /foo" => 0
  },
  once_or_more: %{
    "GET /foo" => 0
  }
}

list_of_expectations
|> Enum.flat_map(fn({expectation_type, urls}) ->
  case expectation_type do
    :once ->
      urls
      |> Enum.filter(fn({_, count}) -> count != 1 end)
      |> Enum.map(fn {url, count} -> "Expected '#{url}' to be called once, called #{count} times." end)
    :once_or_more ->
      urls
      |> Enum.filter(fn({_, count}) -> count == 0 end)
      |> Enum.map(fn {url, count} -> "Expected '#{url}' to be called more than once, called #{count} times." end)
  end
end)
|> Enum.join("\n")
|> IO.puts

# Output:
#
# Expected 'GET /bar' to be called once, called 0 times.
# Expected 'POST /foo' to be called once, called 0 times.
# Expected 'GET /foo' to be called more than once, called 0 times.
```

**Comment by alco** [comment]
@gmile You're on the right track. One thing I would do differently is to keep all expectations for the same Bypass instance in a single namespace. In other words, instead of this

```elixir
list_of_expectations = %{
  once: %{
    "GET /bar" => 0,
    "POST /foo" => 0
  },
  once_or_more: %{
    "GET /foo" => 0
  }
}
```

we want this

```elixir
list_of_expectations = %{
  {"GET", "/bar"} => {:once, 0},
  {["PUT", "POST"],  "/foo"} => {:once, 0},
  {"GET", "/foo"} => {:once_or_more, 0},
}
```

The reason for this is that we won't want to allow the same endpoint to be passed to both `expect` and `expect_once` calls within the same test. Whenever `expect` or `expect_once` is called, Bypass should check if there is already an expectation installed for a given method-path pair and raise an error immediately.

Similarly, if a endpoint that is expected to be triggered only once is triggered for the second time, we should raise an error immediately.

**Comment by gmile** [comment]
This format makes total sense.
```
list_of_expectations = %{
  {"GET", "/bar"} => {:once, 0},
  {["PUT", "POST"], "/foo"} => {:once, 0},
  {"GET", "/foo"} => {:once_or_more, 0},
}
```
One thing I'd add would be an implementation detail – can we not _zip_ the structure, and keep it completely _flat_? No matter how user specified the syntax

```
list_of_expectations = %{
  {"GET", "/bar"} => {:once, 0},
  {"PUT", "/foo"} => {:once, 0},
  {"POST", "/foo"} => {:once, 0},
  {"GET", "/foo"} => {:once_or_more, 0}
}
```
Reason I'm asking for this is that I _think_ it's simpler to traverse. Also, I'm not even sure how to count http calls given this: `{["PUT", "POST"], "/foo"} => {:once, 0}` – which will be solved by relying on a normalized structure I'm proposing.

**Comment by alco** [comment]
@gmile Feel free to do what makes more sense implementation-wise.

**Comment by alanvoss** [comment]
Has anyone started implementing this yet, out of curiosity?  I'd love to see this functionality.  Potentially I can help.

**Comment by gmile** [comment]
@alanvoss I was planning, and there was some work done, but I've never finished it. Please go ahead!

**Comment by alanvoss** [comment]
I am polishing up my work now, but I believe I have a functioning version of what is requested here, and which obviates the need for my other PR.  It will be posted soon.

**Comment by alanvoss** [comment]
Please see https://github.com/PSPDFKit-labs/bypass/pull/36 .
