### ISSUE TITLE
Running concurrent tests

### ISSUE THREAD

**Issue by svarlet** [PSPDFKit-labs/bypass#19]
Hi,

I've followed your Readme example and realised that it's either not possible or not explained whether it is possible to run tests concurrently with bypass. The following is an example:

```elixir
defmodule MyTest do
  use ExUnit.Case, async: true

  setup do 
    bypass = Bypass.open
    Application.put_env(:my_app, :hostname, "http://localhost:#{bypass.port}"
    {:ok, bypass: bypass}
  end

  test "a test", %{bypass: bypass} do
    ...
  end

  test "another test", %{bypass: bypass} do
    ...
  end
end
```

In this example, both test setups are updating `Application` concurrently. It seems it hasn't caused any issues in my tests yet though.

Am I missing something ? Is there a workaround or should I stop using `async: true` ?

**Comment by svarlet** [comment]
Also, I'm not convinced this approach is good as it will leave the hostname value changed forever instead of resetting it to the value before the setup call.

**Comment by svarlet** [comment]
I would discourage the use of Application.put_env as (correct me if I'm wrong) it won't play well with concurrent tests all reading and writing this configuration value concurrently. Therefore, I would either mention this in the README or use another strategy in it.

Personally, I found that a safe and concurrent solution is to pass a "client" map to the function under test. This map notably specifies the desired hostname. It can be initialised in the `setup` function of my test after the call to `Bypass.open`.

Here is an example:

```elixir
setup context do
    bypass = Bypass.open
    client = %Client{
        hostname: "http://localhost:#{bypass.port}",
        credentials: %Credentials{...}
    }
    context
    |> Map.put(:bypass, bypass)
    |> Map.put(:client, client)
end

test "this is my test", context do
    Bypass.expect context.bypass, fn conn ->
      #assert ...
    end
    MyModule.my_function(context.client, param1, param2, param3)
end
```

The drawback is `my_function` 's api now takes an extra parameter that is not directly related to its goal. Yet, since it's a map it can easily gather many other properties (such as credentials!) without impacting even more the api of the module/function.

This works well in my situation where I am writing a client for a remote API (ex_tumblr).

**Comment by rjgroller** [comment]
I had some luck passing `false` to the `:persistent` option for [Application.put_env](http://elixir-lang.org/docs/stable/elixir/Application.html#put_env/4).

**Comment by alco** [comment]
Hi @svarlet.

You're absolutely right: application env is a shared resource and it will naturally lead to race conditions when running multiple tests concurrently.

If you're testing an API client that relies on finding the endpoint URL or port in the application env, then there's nothing Bypass can do there. Such clients should be tested with sequential tests.

In response to your question I have updated our README to build the endpoint URL in each individual test case. Thank you for raising this issue.
