### ISSUE TITLE
Specifying port for new bypass instance

### ISSUE THREAD

**Issue by cmwilhelm** [PSPDFKit-labs/bypass#25]
Hey, we've been working on standing up an Elixir application and found bypass a few days ago (great work, it's been very helpful so far!).

I was curious to know if there's been any interest / discussion about allowing users to specify a desired port to open a new Bypass on? We're using some libs that wrap http clients, but bake in their config at build time so the `Application.put_env()` model in your examples is a no-go for passing in the port `Bypass.open` assigns.

**Comment by alco** [comment]
@cmwilhelm We haven't gotten any request for allowing this so far. And unfortunately Bypass does not permit passing it a specific port as is.

As a stop-gap solution, you could fork the project and change [this code](https://github.com/PSPDFKit-labs/bypass/blob/87721c7ff56e6b307cb0e04d8a44666ce502b28b/lib/bypass/instance.ex#L33-L36) to get the value for `port` from the caller.

Long-term we would be OK with providing a public API to assign a fixed port to a Bypass instance.
