### ISSUE TITLE
Working example?

### ISSUE THREAD

**Issue by diogovk** [PSPDFKit-labs/bypass#28]
In the README, there's an example of how to use bypass to test a module, in the case TwitterClient.
The thing is, I'm not sure how TwitterClient is implemented, and should I go for implementing a similar module.
I understand that it involves using an http client.

I think a working example would be great for people trying to learn how to use bypass.
What do you think?

**Comment by alco** [comment]
Hi. You can use Bypass to test any kind of HTTP client. All you need to do is make sure it connects to the spawned Bypass instance which listens on `"http://localhost:#{bypass.port}"`.

In the example in the Readme we show a hypothetical twitter client that is initialized with the correct URL in each test case. A minimal working example would just use `httpc` to send a request to `"http://localhost:#{bypass.port}"`.

I recommend watching Martin's lightning talk where he shows a a stub implementation for a Twitter client and how it's tested using Bypass - https://www.youtube.com/watch?v=Kh6m4EQBb0k
