### ISSUE TITLE
debug_log should check the config at runtime (not compile time)

### ISSUE THREAD

**Issue by ajvondrak** [PSPDFKit-labs/bypass#29]
I'm having troubles making a minimal repro, but my basic problem is that:
1. I have an app that depends on `{:bypass, github: "PSPDFKit-labs/bypass", ref: "6ed6bee81e48653bcca31f03dec9506889fc44c6", only: :test}`.
2. I have a config/test.exs with `config :bypass, enable_debug_log: false`.
3. I run `mix test`, no debug logs (this is expected).
4. I change config/test.exs to `config :bypass, enable_debug_log: true`.
5. Run `mix test`, **still** no debug logs (unexpected).
6. Logs are not turned on until I completely reinstall bypass with `MIX_ENV=test mix do deps.clean bypass, deps.get, deps.compile bypass`.
7. Similarly, switching `true` to `false` will take no effect until I recompile bypass.

I believe the underlying issue is that the `debug_log` macro is getting compiled with one environment setting, then bypass isn't getting recompiled in between different `mix test` runs. Ergo, the different config has no effect on the compiled bypass app.

Editing the `deps/bypass` contents locally, this fixes my issue (i.e., after making this change then recompiling with `MIX_ENV=test mix deps.compile bypass`, my config changes take immediate effect on subsequent `mix test` runs):

``` diff
diff --git a/lib/bypass/utils.ex b/lib/bypass/utils.ex
index 915e7f5..24419a5 100644
--- a/lib/bypass/utils.ex
+++ b/lib/bypass/utils.ex
@@ -2,16 +2,12 @@ defmodule Bypass.Utils do
   @moduledoc false

   Application.load(:bypass)
-  if Application.get_env(:bypass, :enable_debug_log, false) do
-    defmacro debug_log(msg) do
-      quote bind_quoted: [msg: msg] do
+  defmacro debug_log(msg) do
+    quote bind_quoted: [msg: msg] do
+      if Application.get_env(:bypass, :enable_debug_log, false) do
         require Logger
         Logger.debug ["[bypass] ", msg]
       end
     end
-  else
-    defmacro debug_log(_msg) do
-      :ok
-    end
   end
 end
```

Again, sorry to not have a repro. Dunno what special alignment of moons I have in my actual project that's causing this issue, because I can't seem to trigger it with a "blank" app. But I think my reasoning is sound.

Thoughts?

**Comment by alco** [comment]
`debug_log` is a macro just like `Logger.debug` is. When you change the config, doing `mix deps.compile --force bypass` should be enough to recompile it.

The purpose of `debug_log` is to help track down bugs in Bypass or in the way it is used. It should not be enabled during regular test runs so compiling out all logging calls makes sense here.

**Comment by dustinfarris** [comment]
This was confusing for me too.  Thanks for filing this issue @ajvondrak so something came up when I searched for it!
