### ISSUE TITLE
not working on travis?

### ISSUE THREAD

**Issue by peillis** [PSPDFKit-labs/bypass#31]
I have some tests with bypass that work perfectly on localhost, but when running on travis many time I get this error:

*\* (FunctionClauseError) no function clause matching in Bypass.expect/2
     stacktrace:
       (bypass) lib/bypass.ex:38: Bypass.expect({:error, :eaddrinuse}, ...

**Comment by anthonator** [comment]
I'm randomly getting this every now and then as well

**Comment by alco** [comment]
Please create a new issue with some specifics if you still experience this.
