### ISSUE TITLE
New version?

### ISSUE THREAD

**Issue by alexpusch** [PSPDFKit-labs/bypass#32]
v0.5.1 was released long ago. There were several interesting additions since then.

Could you release a new version?

**Comment by anthonator** [comment]
This would be great

**Comment by anthonator** [comment]
Any chance to we can get a new version?

**Comment by mneumark** [comment]
👍

**Comment by swelham** [comment]
:+1: Also appears to have been a while since a commit or PR's has been merged.

Is this project still going to be maintained?

**Comment by alco** [comment]
Hey everyone. Version 0.6.0 is up on Hex. Thanks for your patience.
