### ISSUE TITLE
Connection closure using Bypass with CircleCI and Heroku

### ISSUE THREAD

**Issue by wulymammoth** [PSPDFKit-labs/bypass#42]
**Erlang v20**
**Elixir v1.4.5**
**Phoenix v1.3.0-rc.2**
**Bypass v0.7.0**

We're getting intermittent build failures with CircleCI and Heroku. The following is the error that I cannot reproduce locally:
```
** (EXIT from #PID<0.796.0>) an exception was raised:
         ** (HTTPoison.Error) :closed
             (httpoison) lib/httpoison.ex:66: HTTPoison.request!/5
             (myapp) lib/myapp/api.ex:102: Client.API.request/6
             (myapp) lib/myapp/api.ex:90: Client.API.get!/3
             (myapp) lib/myapp/api.ex:58: Client.list_currencies!/1
             (con_cache) lib/con_cache/operations.ex:202: ConCache.Operations.dirty_get_or_store/3
             (con_cache) lib/con_cache/lock.ex:31: ConCache.Lock.exec/4
             (elixir) lib/task/supervised.ex:85: Task.Supervised.do_apply/2
             (elixir) lib/task/supervised.ex:36: Task.Supervised.reply/5
             (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
.18:12:38.524 [error] Task #PID<0.806.0> started from #PID<0.796.0> terminating
```

**config/test.exs**
```elixir
# Bypass
config :bypass, port: 1234
```

**HelperModule**
```elixir
bypass = Bypass.open(port: Application.get_env(:bypass, :port))
Bypass.expect bypass, "GET", "/v2/foo", fn conn ->
      Plug.Conn.resp(conn, 200, File.read!("#{File.cwd!}/test/bypass/foo.json"))
    end
end
```

**sometest.exs**
```elixir
setup do
  bypass = Bypass.open(port: Application.get_env(:bypass, :port))
  {:ok, bypass: bypass}
end
```

Anybody encounter issues with their CI and/or with Heroku? Have any ideas about where to go from here?

**Comment by MSch** [comment]
My suspicion is that it's related to Hackney, possibly https://github.com/benoitc/hackney/issues/398

**Comment by ghbutton** [comment]
Do you think so, we are only making a few requests while the hackney issue sites thousands of requests per second

**Comment by MSch** [comment]
Can you post one of your tests that fails intermittently? I would expect this error only if the test process that started bypass terminates before the request is returned & processed by hackney.

**Comment by Hajto** [comment]
I have the same issue

**Comment by sjoconnor** [comment]
**Elixir - 1.5.2**
**Bypass - 0.8.1**
**Phoenix - 1.3.0**

I seem to be experiencing this as well. I have a couple of tests that are only failing our CI server, but always pass locally (El Capitan). I'm using Bypass with Wallaby to browser test against external services. Unfortunately, there doesn't seem to be much in the logs other than the following:

```
[error] #PID<0.5260.0> running Bypass.Plug terminated

** (exit) an exception was raised:
    ** (WithClauseError) no with clause matching: {:ok, %HTTPoison.Response{body: "", headers: [{"server", "Cowboy"}, {"date", "Fri, 01 Dec 2017 19:39:10 GMT"}, {"content-length", "0"}], request_url: "http://localhost:5000/servers", status_code: 500}}
```

After that first failure tests most tests wills till pass, but some will fail.

**Comment by ream88** [comment]
Is this still a problem?

**Comment by wulymammoth** [comment]
@ream88 There hasn't been any reports since 2017. May be fair to close and have a new issue created?

**Comment by wulymammoth** [comment]
No new reports since 2017. Closing for now
