### ISSUE TITLE
QUESTION: Force header

### ISSUE THREAD

**Issue by veverkap** [PSPDFKit-labs/bypass#47]
I am trying to run tests against an API that returns JSON.  I am setting up an individual test like so:

```elixir
      Bypass.expect bypass, fn conn ->
        conn
        |> Plug.Conn.put_resp_header("content-type", "application/json")
        |> Plug.Conn.resp(200, json_response)
      end
```

Rather than have to add that `put_resp_header/3` call in every test, is there a way to do this in my setup?

**Comment by MSch** [comment]
There is no way, this is something that can be beautifully expressed directly in Elixir:

```elixir
defp expect_json(bypass, fun) do
  Bypass.expect bypass, fn conn ->
    conn = Plug.Conn.put_resp_header("content-type", "application/json")
    fun.(conn)
  end
end
```

(I'm closing this issue, since it's a question, but I'd love to know if my answer solved your problem)

**Comment by veverkap** [comment]
It did solve my problem, thanks!

```elixir

  def expect_json(bypass, fun) do
    Bypass.expect bypass, fn conn ->
      conn = Plug.Conn.put_resp_header(
        conn,
        "content-type",
        "application/json")
      fun.(conn)
    end
  end
```

https://github.com/veverkap/cloudinex/commit/4ad27fbee9edf7cc6bfbf55092f96aed6e0ee18f
