### ISSUE TITLE
Help: Unable to match request

### ISSUE THREAD

**Issue by wulymammoth** [PSPDFKit-labs/bypass#48]
I've started two instances of Bypass one for each external service that a given controller action in Phoenix hits. Only one matches, the other returns:
```elixir
%HTTPoison.Response{body: "",
 headers: [{"server", "Cowboy"}, {"date", "Tue, 22 Aug 2017 04:33:50 GMT"},
  {"content-length", "0"}], status_code: 500}
```
I've triple-checked the request method, host, and path, but I can't seem to get it to work. Am I missing something? 

The service is set using an application env var which I set at run-time. I've attempted this in a test in IEx and set up a Bypass expect for the `/` (home) path to return a 200 response, but keep receiving the above. I'm out of luck here. 

I call the external service's `/` path with a `GET` from a private function/plug inside my Phoenix controller, but I fail to see why that might be the issue.

**Comment by MSch** [comment]
Hm, is there anything in the debug log? If cowboy returns with 500 usually there was a crash which should be logged, if you've configured `Logger` to do so.

**Comment by veverkap** [comment]
I've had similar issues using Bypass with setting an application environmental variable.  It has something to do with asynchronous test runs.

We've had luck with those tests by setting async to false in the module definition

```elixir
use ExUnit.Case, async: false
```

**Comment by ream88** [comment]
@wulymammoth did the fix @veverkap mentioned worked for you?

**Comment by wulymammoth** [comment]
IIRC going synchronous worked, but I wouldn't consider it a fix. However, I think this is oaky to close because it is 3 years old without any activity
