### ISSUE TITLE
Issue in  dispatch_awaiting_callers/1

### ISSUE THREAD

**Issue by anagromataf** [PSPDFKit-labs/bypass#53]
There is a bug in `Bypass.Instance.dispatch_awaiting_callers/1`. The reference of the server in `GenServer.stop(:normal)` is missing:

https://github.com/PSPDFKit-labs/bypass/blob/master/lib/bypass/instance.ex#L298

```
if length(exit_callers) > 0 do
  {result, _updated_state} = do_exit(state)
  Enum.each(exit_callers, &(GenServer.reply(&1, result)))
  GenServer.stop(:normal)
end
```

What is the expected behavior? I would guess that the `ref`of the state should be used.

**Comment by avni510** [comment]
I wanted to follow up on this issue. Can `GenServer.stop(:normal)` be deleted?

**Comment by ream88** [comment]
@anagromataf @avni510 do you have an example which triggers this bug?

**Comment by anagromataf** [comment]
> @anagromataf @avni510 do you have an example which triggers this bug?

Sorry, it's way to long ago.
