### ISSUE TITLE
Asserting 0 Requests

### ISSUE THREAD

**Issue by veverkap** [PSPDFKit-labs/bypass#54]
Is there a way with bypass to assert that NO http requests were made?

We have a test in which we want to assert that no requests were made to an api.  We can get the normal error: 

```
     No HTTP request arrived at Bypass
     stacktrace:
       (bypass) lib/bypass.ex:86: Bypass.do_verify_expectations/2
```

But we'd like the presence of that to be an assertion.

Is that possible?

**Comment by cartoloupe** [comment]
This seems to be addressed here: https://github.com/PSPDFKit-labs/bypass/issues/14

**Comment by veverkap** [comment]
That it does @cartoloupe.

Thanks!
