### ISSUE TITLE
0.9 release

### ISSUE THREAD

**Issue by keathley** [PSPDFKit-labs/bypass#64]
Hey y'all. Thanks so much for this library. We use it very heavily. I was wondering if it would be possible to get a 0.9 release which would include the new `stub` function. If there's other stuff that needs to be finished up before that then I'm happy to help with those changes.

Thanks again for the work you put into this library.

**Comment by chulkilee** [comment]
Found https://hex.pm/packages/bypass/0.9.0 but no entry in CHANGELOG.md, no git tag, no github release.. and even no related git commit. Hm..

**Comment by MSch** [comment]
Thanks for the heads up, I forgot to push the release commit + tag.
