### ISSUE TITLE
 :simple_one_for_one strategy is deprecated

### ISSUE THREAD

**Issue by anthonator** [PSPDFKit-labs/bypass#86]
The `:simple_one_for_one` supervisor strategy was deprecated in Elixir 1.10. It's recommended to use `DynamicSupervisor` instead which was introduced in Elixir 1.6. As a result of this deprecation I've started to see the following warning whenever I run my test suite.

```
warning: :simple_one_for_one strategy is deprecated, please use DynamicSupervisor instead
  (elixir 1.10.1) lib/supervisor.ex:604: Supervisor.init/2
  (elixir 1.10.1) lib/supervisor.ex:556: Supervisor.start_link/2
  (kernel 6.5.1) application_master.erl:277: :application_master.start_it_old/4
```

I'd be happy to work on this if you'd accept a pull request.

**Comment by ream88** [comment]
Your PR is merged, thx a lot @anthonator
