### ISSUE TITLE
The future of bypass

### ISSUE THREAD

**Issue by ream88** [PSPDFKit-labs/bypass#88]
Hey everybody, 

Today @MSch and I had a nice talk about the future of bypass. And we have awesome news to share: I will join the bypass team and help shape its future from now on! Of course @MSch and the rest of the awesome @PSPDFKit team aren't going anywhere, but for now I'll be the primary contact person for all your bypass related things.

For the start we want to clean up the backlog by releasing a new major version (2.0?). I want to collect all issues and improvements which should definitely be in the next major version into the list below.

If you have any ideas and suggestions, feel free to comment here!

All the best, and a happy Monday! 😊

----

### Code and maintenance improvements: 
- [x] Extend the test matrix to include more recent versions of Elixir: https://github.com/PSPDFKit-labs/bypass/pull/89
- [x] Format code with `mix format`: https://github.com/PSPDFKit-labs/bypass/pull/90
- [x] Format example code
- [x] Add links to source code from docs: https://github.com/PSPDFKit-labs/bypass/pull/79

### Breaking changes:
- [x] Switch from :simple_one_for_one to DynamicSupervisor: https://github.com/PSPDFKit-labs/bypass/pull/87
- [x] Require at least Elixir `1.6`
- [x] Replace gun with mint: https://github.com/PSPDFKit-labs/bypass/pull/99

### New features:
- [x] Allow the redefinition of routes: https://github.com/PSPDFKit-labs/bypass/issues/80
- [x] Make listen interface configurable: https://github.com/PSPDFKit-labs/bypass/pull/70
- [x] Add SO_REUSEPORT: https://github.com/PSPDFKit-labs/bypass/pull/77
- [x] Add support for parametric routes: https://github.com/PSPDFKit-labs/bypass/pull/93

**Comment by hewsut** [comment]
Yay! Props to you and @MSch both. Thanks for your efforts.

**Comment by lucacorti** [comment]
TLS support with automatic SSL certificates setup.

I need this to test my HTTP/2 implementation and would be willing to contribute.

**Comment by chrismcg** [comment]
Thanks for taking this on. I love bypass and it's great to see it getting updated.

**Comment by ream88** [comment]
@chrismcg just give me a few more days, I want to go through all issues in the backlog! 😊

**Comment by chrismcg** [comment]
@ream88 please don't take my comment as any kind of pressure to ship! I'm just happy to see a great lib get some love. I came here to see if there was a PR for the DynamicSupervisor deprecation warning so to see all the work that's been done in addition to that is great.

**Comment by agramichael** [comment]
@ream88 any possibility of making it so that within one test I can stack two expect_once's so that the first call to the given route gets my first expect_once and the second call gets the second expect_once? 
Currently the second expect_once would just redefine the first expect_once and I would get an error because the route is called twice.

**Comment by ream88** [comment]
@agramichael Is https://github.com/PSPDFKit-labs/bypass/issues/80 fixing this for you? Can you try out the `master` branch? 😊

**Comment by agramichael** [comment]
@ream88 that fix has been very helpful! But it's not quite what I was thinking. That allows users to redefine what the response is for the route but still doesn't allow setting multiple responses for the same route, and consuming them in order.

**Comment by mrdougwright** [comment]
> @ream88 that fix has been very helpful! But it's not quite what I was thinking. That allows users to redefine what the response is for the route but still doesn't allow setting multiple responses for the same route, and consuming them in order.

I believe I'm having the exact same issue. We've added a Plug to our main controller that calls (and caches!) out to our graphql API. This now adds an extra call to all of our controller tests, which breaks their call expectations.

Since the route is the same, if we could set and check multiple responses for the same route, we could update our Bypass wrapper in one place.

**Comment by ream88** [comment]
@agramichael @mrdougwright I moved the conversation to a new issue: #95
