### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by josevalim** [PSPDFKit-labs/bypass#97]
Hi, thank you so much for bypass!

bypass master does not emit warnings on Elixir v1.10 (as well as Elixir master), so would it be possible to do a new release for those who want to be warning free? Thank you! :heart:

**Comment by anthonator** [comment]
Any chance we could get a response from the Bypass team?

**Comment by ream88** [comment]
v2.0.0 is now live!

**Comment by josevalim** [comment]
@ream88 thank you for the release! I have just given it a try and unfortunately bypass locks itself to a very old cowlib version (~> 1.0.x while latest is ~> 2.9.x). I will work on a PR soon but I am afraid 2.0.1 will be required. :)

**Comment by josevalim** [comment]
@ream88 PR sent here: #101. The PR still supports both Cowboy versions but if you want to require `plug_cowboy ~> 2.0` that would also be fine. The upcoming Phoenix version also won't work with Cowboy v1.0. It is probably best to retire version 2.0.0.
