### ISSUE TITLE
Move primary documentation out of the README

### ISSUE THREAD

**Issue by mhanberg** [PSPDFKit-labs/bypass#98]
The primary documentation seems to be in the readme instead of on hexdocs.

If there is interest, I can submit a PR that adds what is in the README to the `Bypass` `@moduledoc` via [this pattern](https://github.com/dashbitco/nimble_pool/blob/master/lib/nimble_pool.ex#L1..L6) or move the docs for each function into their respective `@doc` blocks.

Let me know what you think!

Cheers 🍻

**Comment by ream88** [comment]
Yes, any help would be helpful 😜😊

**Comment by ream88** [comment]
This is now done and live! 😊
